# Use an official Node.js image with build tools
FROM node:18-bullseye

# Set working directory
WORKDIR /app


# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies (force wrtc to build from source)
# RUN npm install

# RUN npm install --build-from-source wrtc

RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

RUN npm install -g node-pre-gyp
RUN npm install --build-from-source wrtc
RUN npm install


# Copy the rest of the app
COPY . .

# Expose the port your app runs on
EXPOSE 4000

# Start the server
CMD ["npm", "start"]
